
import { Post } from "./types";

export const placeholderPosts: Post[] = [
  {
    id: "1",
    user_id: "user-1",
    title: "First Kicks!",
    content: "Just felt the baby kick for the first time! Such an amazing feeling. Can't wait to meet our little one. 💕",
    image_url: "https://images.unsplash.com/photo-1649972904349-6e44c42644a7?w=400&h=300&fit=crop",
    mood: "excited",
    hashtags: ["FirstKicks", "PregnancyJourney"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 24,
    comments_count: 8,
    shares_count: 2,
    saves_count: 5,
    views_count: 156,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Sarah",
      last_name: "Johnson",
      avatar_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=150&h=150&fit=crop&crop=face",
      pregnancy_weeks: 16,
    }
  },
  {
    id: "2",
    user_id: "user-2",
    title: "Sleep Struggles",
    content: "Is anyone else struggling with sleep lately? 😅 Tips welcome!",
    mood: "tired",
    hashtags: ["SleepHelp", "PregnancyTips"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 13,
    comments_count: 4,
    shares_count: 1,
    saves_count: 3,
    views_count: 89,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Chloe",
      last_name: "Adebayo",
      avatar_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&h=150&fit=crop&crop=face",
      pregnancy_weeks: 22,
    }
  },
  {
    id: "3",
    user_id: "user-3",
    title: "Daily Reminder",
    content: "Reminder: Your body is amazing. Rest is productive. 🌸",
    mood: "hopeful",
    hashtags: ["SelfCare", "PositiveVibes"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 39,
    comments_count: 12,
    shares_count: 8,
    saves_count: 15,
    views_count: 234,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "T.K.",
      last_name: "",
      avatar_url: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=150&h=150&fit=crop&crop=face",
      pregnancy_weeks: 18,
    }
  },
  {
    id: "4",
    user_id: "user-4",
    title: "Meditation Success",
    content: "This meditation in the wellness tab actually helped me calm down today. Highly recommend.",
    link_url: "https://wellnest.app/mental",
    link_title: "WellNest Mental Wellness",
    mood: "grateful",
    hashtags: ["Meditation", "MentalHealth"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 17,
    comments_count: 3,
    shares_count: 2,
    saves_count: 8,
    views_count: 98,
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Ava",
      last_name: "Chen",
      avatar_url: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=150&h=150&fit=crop&crop=face",
      pregnancy_weeks: 10,
    }
  },
  {
    id: "5",
    user_id: "user-5",
    title: "Inclusive Space",
    content: "As a non-binary parent-to-be, I really appreciate how inclusive this platform is. Thank you for seeing us. ✨",
    mood: "grateful",
    hashtags: ["Inclusion", "NonBinary", "Community"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 45,
    comments_count: 11,
    shares_count: 6,
    saves_count: 12,
    views_count: 289,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Jordan",
      last_name: "Ali",
      avatar_url: "https://images.unsplash.com/photo-1721322800607-8c38375eef04?w=150&h=150&fit=crop&crop=face",
      pregnancy_weeks: 9,
      pronouns: "they/them",
    }
  },
  {
    id: "6",
    user_id: "user-6",
    title: "Partner Support",
    content: "My partner is glowing and nesting hard — we've rearranged the living room twice this week! 😂",
    mood: "happy",
    hashtags: ["PartnerSupport", "Nesting"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 19,
    comments_count: 3,
    shares_count: 1,
    saves_count: 4,
    views_count: 76,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Luis",
      last_name: "Hernandez",
      pregnancy_weeks: 14,
    }
  },
  {
    id: "7",
    user_id: "user-7",
    title: "Prenatal Yoga",
    content: "Just had a prenatal yoga session. Felt incredible after a long day. Highly recommend! 🧘🏾‍♀️",
    mood: "happy",
    hashtags: ["PrenatalYoga", "SelfCare"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 33,
    comments_count: 6,
    shares_count: 4,
    saves_count: 10,
    views_count: 134,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Anika",
      last_name: "Patel",
      pregnancy_weeks: 27,
    }
  },
  {
    id: "8",
    user_id: "user-8",
    title: "App Features",
    content: "Started using the reminders feature for supplements and water intake. Game changer 💧",
    link_url: "https://wellnest.app/health",
    link_title: "WellNest Health Tracking",
    mood: "grateful",
    hashtags: ["HealthTracking", "Reminders"],
    visibility: "public",
    is_anonymous: false,
    likes_count: 21,
    comments_count: 2,
    shares_count: 3,
    saves_count: 7,
    views_count: 91,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: {
      first_name: "Bisi",
      last_name: "Okonkwo",
      pregnancy_weeks: 12,
    }
  }
];
