
import jsPDF from 'jspdf';

export interface HealthRecord {
  id: string;
  created_at: string;
  type: 'physical' | 'mental';
  data: any;
}

export const exportRecordAsPDF = (record: HealthRecord) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(91, 54, 115); // Primary color
  doc.text('WellNest Health Record', pageWidth / 2, 30, { align: 'center' });
  
  // Record type and date
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  const recordType = record.type === 'physical' ? 'Physical Health' : 'Mental Health';
  doc.text(`Record Type: ${recordType}`, 20, 50);
  
  const date = new Date(record.created_at).toLocaleString();
  doc.text(`Date: ${date}`, 20, 65);
  
  // Content
  doc.setFontSize(12);
  let yPos = 85;
  
  if (record.type === 'physical') {
    doc.text('Physical Health Data:', 20, yPos);
    yPos += 15;
    
    if (record.data.age) {
      doc.text(`Age: ${record.data.age} years`, 25, yPos);
      yPos += 10;
    }
    if (record.data.heartbeat) {
      doc.text(`Heart Rate: ${record.data.heartbeat} bpm`, 25, yPos);
      yPos += 10;
    }
    if (record.data.systolic && record.data.diastolic) {
      doc.text(`Blood Pressure: ${record.data.systolic}/${record.data.diastolic} mmHg`, 25, yPos);
      yPos += 10;
    }
    if (record.data.blood_pressure) {
      doc.text(`Blood Pressure: ${record.data.blood_pressure}`, 25, yPos);
      yPos += 10;
    }
  } else {
    doc.text('Mental Health Data:', 20, yPos);
    yPos += 15;
    
    if (record.data.epds_score !== null && record.data.epds_score !== undefined) {
      doc.text(`EPDS Score: ${record.data.epds_score}`, 25, yPos);
      yPos += 15;
    }
    
    if (record.data.responses && typeof record.data.responses === 'object') {
      doc.text('Survey Responses:', 25, yPos);
      yPos += 10;
      
      Object.entries(record.data.responses).forEach(([key, value], index) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = 30;
        }
        doc.text(`${index + 1}. ${key}: ${value}`, 30, yPos);
        yPos += 8;
      });
    }
  }
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by WellNest', pageWidth / 2, doc.internal.pageSize.height - 20, { align: 'center' });
  
  // Download
  const fileName = `wellnest-${record.type}-${new Date(record.created_at).toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

export const exportRecordAsCSV = (record: HealthRecord) => {
  const date = new Date(record.created_at).toISOString();
  let csvContent = 'Field,Value\n';
  csvContent += `Record Type,${record.type === 'physical' ? 'Physical Health' : 'Mental Health'}\n`;
  csvContent += `Date,${date}\n`;
  
  if (record.type === 'physical') {
    if (record.data.age) csvContent += `Age,${record.data.age} years\n`;
    if (record.data.heartbeat) csvContent += `Heart Rate,${record.data.heartbeat} bpm\n`;
    if (record.data.systolic) csvContent += `Systolic Pressure,${record.data.systolic} mmHg\n`;
    if (record.data.diastolic) csvContent += `Diastolic Pressure,${record.data.diastolic} mmHg\n`;
    if (record.data.blood_pressure) csvContent += `Blood Pressure,${record.data.blood_pressure}\n`;
  } else {
    if (record.data.epds_score !== null && record.data.epds_score !== undefined) {
      csvContent += `EPDS Score,${record.data.epds_score}\n`;
    }
    
    if (record.data.responses && typeof record.data.responses === 'object') {
      Object.entries(record.data.responses).forEach(([key, value]) => {
        csvContent += `${key},"${value}"\n`;
      });
    }
  }
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `wellnest-${record.type}-${new Date(record.created_at).toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportAllRecordsAsCSV = (records: HealthRecord[], filterType: string) => {
  if (records.length === 0) return;
  
  let csvContent = 'Date,Type,';
  
  // Create headers based on record types
  const hasPhysical = records.some(r => r.type === 'physical');
  const hasMental = records.some(r => r.type === 'mental');
  
  if (hasPhysical) {
    csvContent += 'Age,Heart Rate,Systolic,Diastolic,Blood Pressure,';
  }
  if (hasMental) {
    csvContent += 'EPDS Score,Survey Responses';
  }
  csvContent += '\n';
  
  records.forEach(record => {
    const date = new Date(record.created_at).toISOString();
    const type = record.type === 'physical' ? 'Physical' : 'Mental';
    let row = `${date},${type},`;
    
    if (record.type === 'physical') {
      row += `${record.data.age || ''},${record.data.heartbeat || ''},${record.data.systolic || ''},${record.data.diastolic || ''},${record.data.blood_pressure || ''},`;
      if (hasMental) row += ','; // Empty mental columns
    } else {
      if (hasPhysical) row += ',,,,,'; // Empty physical columns
      row += `${record.data.epds_score || ''},"${record.data.responses ? JSON.stringify(record.data.responses).replace(/"/g, '""') : ''}"`;
    }
    
    csvContent += row + '\n';
  });
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `wellnest-all-records-${filterType}-${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
